### ISSUE TITLE
Improving the APIs that take &Path

### ISSUE THREAD

**Issue by lilianmoraru** [durka/foreman#4]
I tried to do this task myself but the macros are overly complicated.

Could you please make the APIs that take `&Path`, to look something like this?:
From:
```rust
pub fn rerun(n: &Path)
```
into
```rust
pub fn rerun<S: AsRef<OsStr> + ?Sized>(n: &S)
```

This helps transform these APIs from:
```rust
use std::path::Path;
rerun(Path::new("Cargo.toml"));
```
into just(note, no need for `use std::path::Path`):
```rust
rerun("Cargo.toml");
```

**Comment by durka** [comment]
Working on overhauling the macros to hopefully make more sense and support this :)

**Comment by durka** [comment]
This is in 0.4.0. But I think the macros may have gotten worse, not better 😳 

Thanks for the suggestion!
